set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_C_COMPILER /opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER /opt/devkitpro/devkitARM/bin/arm-none-eabi-g++)
set(DEVKITPRO /opt/devkitpro)
set(DEVKITARM /opt/devkitpro/devkitARM)